# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 449)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/* Basic */\n"
                                 "\n"
                                 "QWidget {\n"
                                 "    background-color: rgb(23, 23, 23);\n"
                                 "    color: #fff;\n"
                                 "    border-radius: 9px;\n"
                                 "}\n"
                                 "\n"
                                 "QMainWindow > QWidget {\n"
                                 "    background-color: rgb(20, 20, 20) !important;\n"
                                 "    color: #fff !important;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton,\n"
                                 "QToolButton,\n"
                                 "QCheckBox {\n"
                                 "    background-color: rgb(27, 27, 27);\n"
                                 "    border-radius: 5px;\n"
                                 "    outline: none;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox,\n"
                                 "QSpinBox,\n"
                                 "QDoubleSpinBox,\n"
                                 "QTimeEdit,\n"
                                 "QDateEdit,\n"
                                 "QDateTimeEdit,\n"
                                 "QLineEdit,\n"
                                 "QTextEdit,\n"
                                 "QPlainTextEdit,\n"
                                 "QKeySequenceEdit {\n"
                                 "    background-color: rgb(28, 28, 28);\n"
                                 "    border-radius: 5px;\n"
                                 "    outline: none;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QPushButton:hover,\n"
                                 "QToolButton:hover,\n"
                                 "QRadioButton:hover,\n"
                                 "QCheckBox:hover,\n"
                                 "QComboBox:hover,\n"
                                 "QLineEdit:hover,\n"
                                 "\n"
                                 "QPlainTextEdit:hover,\n"
                                 "QSpinBox:hover,\n"
                                 "QDoubleSpinBox:hover,\n"
                                 "QTimeEdit:hover,\n"
                                 "QDateEdit:hover,\n"
                                 "QDateTimeEdit:hover,\n"
                                 "QKeySequenceEdit:hover {\n"
                                 "    background-color: rgb(32, 32, 32);\n"
                                 "}\n"
                                 "\n"
                                 "QTextEdit:hover {\n"
                                 "    background-color: rgb(25, 25, 25);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed,\n"
                                 "QToolButton:pressed,\n"
                                 "QRadioButton:pressed,\n"
                                 "QCheckBox:pressed,\n"
                                 "QComboBox:pressed,\n"
                                 "QLineEdit:pressed,\n"
                                 "QTextEdit:pressed,\n"
                                 "QPlainTextEdit:pressed,\n"
                                 "QSpinBox:pressed,\n"
                                 "QDoubleSpinBox:pressed,\n"
                                 "QTimeEdit:pressed,\n"
                                 "QDateEdit:pressed,\n"
                                 "QDateTimeEdit:pressed,\n"
                                 "QKeySequenceEdit:pressed {\n"
                                 "    background-color: rgb(36, 36, 36);\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit:focus,\n"
                                 "QPlainTextEdit:focus,\n"
                                 "QSpinBox:focus,\n"
                                 "QDoubleSpinBox:focus,\n"
                                 "QTimeEdit:focus,\n"
                                 "QDateEdit:focus,\n"
                                 "QDateTimeEdit:focus,\n"
                                 "QKeySequenceEdit:focus {\n"
                                 "    background-color: rgb(30.5, 30.5, 30.5)\n"
                                 "}\n"
                                 "\n"
                                 "QTextEdit:focus {\n"
                                 "    background-color: rgb(28.5, 28.5, 28.5)\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox {\n"
                                 "    padding: 1px 0px 1px 3px;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QComboBox::drop-down\n"
                                 "{\n"
                                 "    border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox::down-arrow {\n"
                                 "    width: 199px;\n"
                                 "    height: 14px;\n"
                                 "}\n"
                                 "\n"
                                 "QRadioButton {\n"
                                 "    background-color: rgb(28, 28, 28);\n"
                                 "    border-radius: 5px;\n"
                                 "}\n"
                                 "\n"
                                 "/* For Frames */\n"
                                 "\n"
                                 "QFrame {\n"
                                 "    background-color: rgb(23, 23, 23);\n"
                                 "    border-radius: 9px;\n"
                                 "}\n"
                                 "\n"
                                 "QFrame > QPushButton,\n"
                                 "QFrame > QPushButton,\n"
                                 "QFrame > QToolButton,\n"
                                 "QFrame > QCheckBox {\n"
                                 "    background-color: rgb(30, 30, 30);\n"
                                 "}\n"
                                 "\n"
                                 "QFrame > QComboBox,\n"
                                 "QFrame > QSpinBox,\n"
                                 "QFrame > QDoubleSpinBox,\n"
                                 "QFrame > QTimeEdit,\n"
                                 "QFrame > QDateEdit,\n"
                                 "QFrame > QDateTimeEdit,\n"
                                 "QFrame > QLineEdit,\n"
                                 "QFrame > QTextEdit,\n"
                                 "QFrame > QPlainTextEdit,\n"
                                 "QFrame > QKeySequenceEdit {\n"
                                 "    background-color: rgb(31, 31, 31);\n"
                                 "    border-radius: 5px;\n"
                                 "    outline: none;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QFrame > QPushButton:hover,\n"
                                 "QFrame > QToolButton:hover,\n"
                                 "QFrame > QRadioButton:hover,\n"
                                 "QFrame > QCheckBox:hover,\n"
                                 "QFrame > QComboBox:hover,\n"
                                 "QFrame > QLineEdit:hover,\n"
                                 "QFrame > QTextEdit:hover,\n"
                                 "QFrame > QPlainTextEdit:hover,\n"
                                 "QFrame > QSpinBox:hover,\n"
                                 "QFrame > QDoubleSpinBox:hover,\n"
                                 "QFrame > QTimeEdit:hover,\n"
                                 "QFrame > QDateEdit:hover,\n"
                                 "QFrame > QDateTimeEdit:hover,\n"
                                 "QFrame > QKeySequenceEdit:hover {\n"
                                 "    background-color: rgb(35, 35, 35);\n"
                                 "}\n"
                                 "\n"
                                 "QFrame > QPushButton:pressed,\n"
                                 "QFrame > QToolButton:pressed,\n"
                                 "QFrame > QRadioButton:pressed,\n"
                                 "QFrame > QCheckBox:pressed,\n"
                                 "QFrame > QComboBox:pressed,\n"
                                 "QFrame > QLineEdit:pressed,\n"
                                 "QFrame > QTextEdit:pressed,\n"
                                 "QFrame > QPlainTextEdit:pressed,\n"
                                 "QFrame > QSpinBox:pressed,\n"
                                 "QFrame > QDoubleSpinBox:pressed,\n"
                                 "QFrame > QTimeEdit:pressed,\n"
                                 "QFrame > QDateEdit:pressed,\n"
                                 "QFrame > QDateTimeEdit:pressed,\n"
                                 "QFrame > QKeySequenceEdit:pressed {\n"
                                 "    background-color: rgb(39, 39, 39);\n"
                                 "}\n"
                                 "\n"
                                 "/* Vertical Scroll Bar */\n"
                                 "\n"
                                 "QScrollBar:vertical {\n"
                                 "    background-color: rgba(25, 25, 25, 0);\n"
                                 "    border: 8px solid rgba(25, 25, 25, 0);\n"
                                 "    width: 7px;\n"
                                 "    max-width: 10px;\n"
                                 "    min-width: 5px;\n"
                                 "    margin: 15px 0 15px 0;\n"
                                 "    border-radius: 7px !important;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar:vertical:hover {\n"
                                 "    background-color: rgba(25, 25, 25, 0.830);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:vertical {\n"
                                 "    background-color: rgb(30, 30, 30);\n"
                                 "    min-height: 30px;\n"
                                 "    border-radius: 7px !important;\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical:hover{\n"
                                 "    background-color: rgb(32, 32, 32);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:vertical:pressed {\n"
                                 "    background-color: rgb(35, 35, 35);\n"
                                 "}\n"
                                 "\n"
                                 "/* Top Button */\n"
                                 "\n"
                                 "QScrollBar::sub-line:vertical {\n"
                                 "    border: none;\n"
                                 "    background-color: transparent;\n"
                                 "    height: 0px;\n"
                                 "    border-top-left-radius: 0px;\n"
                                 "    border-top-right-radius: 0px;\n"
                                 "    width: 0px;\n"
                                 "}\n"
                                 "\n"
                                 "/* Bottom Button */\n"
                                 "\n"
                                 "QScrollBar::add-line:vertical {\n"
                                 "    border: none;\n"
                                 "    background-color: transparent;\n"
                                 "    height: 0px;\n"
                                 "    border-top-left-radius: 0px;\n"
                                 "    border-top-right-radius: 0px;\n"
                                 "    width: 0px;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                 "    background: none;\n"
                                 "}\n"
                                 "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                 "    background: none;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.console_frame = QtWidgets.QFrame(self.centralwidget)
        self.console_frame.setGeometry(QtCore.QRect(361, 60, 241, 371))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.console_frame.setFont(font)
        self.console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_frame.setObjectName("console_frame")
        self.console_text = QtWidgets.QLabel(self.console_frame)
        self.console_text.setGeometry(QtCore.QRect(0, 8, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.console_text.setFont(font)
        self.console_text.setAlignment(QtCore.Qt.AlignCenter)
        self.console_text.setObjectName("console_text")
        self.console = QtWidgets.QTextEdit(self.console_frame)
        self.console.setEnabled(True)
        self.console.setGeometry(QtCore.QRect(6, 34, 230, 331))
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.depth_frame = QtWidgets.QFrame(self.centralwidget)
        self.depth_frame.setGeometry(QtCore.QRect(10, 100, 341, 31))
        self.depth_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.depth_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.depth_frame.setObjectName("depth_frame")
        self.depth_slider = QtWidgets.QSlider(self.depth_frame)
        self.depth_slider.setGeometry(QtCore.QRect(142, 6, 160, 22))
        self.depth_slider.setMinimum(1)
        self.depth_slider.setMaximum(20)
        self.depth_slider.setProperty("value", 1)
        self.depth_slider.setOrientation(QtCore.Qt.Horizontal)
        self.depth_slider.setObjectName("depth_slider")
        self.depth_label = QtWidgets.QLabel(self.depth_frame)
        self.depth_label.setGeometry(QtCore.QRect(10, 5, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.depth_label.setFont(font)
        self.depth_label.setObjectName("depth_label")
        self.depth_value = QtWidgets.QLabel(self.depth_frame)
        self.depth_value.setGeometry(QtCore.QRect(311, 8, 22, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.depth_value.setFont(font)
        self.depth_value.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_value.setObjectName("depth_value")
        self.window_header = QtWidgets.QFrame(self.centralwidget)
        self.window_header.setGeometry(QtCore.QRect(-1, 0, 621, 50))
        self.window_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_header.setObjectName("window_header")
        self.chess_bot_title = QtWidgets.QLabel(self.window_header)
        self.chess_bot_title.setGeometry(QtCore.QRect(19, 11, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chess_bot_title.setFont(font)
        self.chess_bot_title.setObjectName("chess_bot_title")
        self.timeout_frame = QtWidgets.QFrame(self.centralwidget)
        self.timeout_frame.setGeometry(QtCore.QRect(10, 140, 167, 31))
        self.timeout_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeout_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeout_frame.setObjectName("timeout_frame")
        self.timeout_text = QtWidgets.QLabel(self.timeout_frame)
        self.timeout_text.setGeometry(QtCore.QRect(10, 5, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.timeout_text.setFont(font)
        self.timeout_text.setObjectName("timeout_text")
        self.timeout_value = QtWidgets.QLineEdit(self.timeout_frame)
        self.timeout_value.setGeometry(QtCore.QRect(117, 5, 41, 20))

        onlyInt = QtGui.QIntValidator()

        self.timeout_value.setValidator(onlyInt)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.timeout_value.setFont(font)
        self.timeout_value.setAlignment(QtCore.Qt.AlignCenter)
        self.timeout_value.setObjectName("timeout_value")
        self.max_think_time_frame = QtWidgets.QFrame(self.centralwidget)
        self.max_think_time_frame.setGeometry(QtCore.QRect(185, 140, 167, 31))
        self.max_think_time_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.max_think_time_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.max_think_time_frame.setObjectName("max_think_time_frame")
        self.think_time_text = QtWidgets.QLabel(self.max_think_time_frame)
        self.think_time_text.setGeometry(QtCore.QRect(10, 5, 101, 23))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.think_time_text.setFont(font)
        self.think_time_text.setObjectName("think_time_text")
        self.max_think_time_value = QtWidgets.QLineEdit(
            self.max_think_time_frame)
        self.max_think_time_value.setGeometry(QtCore.QRect(117, 5, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.max_think_time_value.setFont(font)
        self.max_think_time_value.setAlignment(QtCore.Qt.AlignCenter)
        self.max_think_time_value.setObjectName("max_think_time_value")

        onlyInt = QtGui.QIntValidator()
        self.max_think_time_value.setValidator(onlyInt)

        self.hotkeys_frame = QtWidgets.QFrame(self.centralwidget)
        self.hotkeys_frame.setGeometry(QtCore.QRect(12, 180, 165, 91))
        self.hotkeys_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hotkeys_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hotkeys_frame.setObjectName("hotkeys_frame")
        self.x_button = QtWidgets.QLabel(self.hotkeys_frame)
        self.x_button.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.x_button.setFont(font)
        self.x_button.setObjectName("x_button")
        self.r_button = QtWidgets.QLabel(self.hotkeys_frame)
        self.r_button.setGeometry(QtCore.QRect(10, 36, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.r_button.setFont(font)
        self.r_button.setObjectName("r_button")
        self.c_button = QtWidgets.QLabel(self.hotkeys_frame)
        self.c_button.setGeometry(QtCore.QRect(10, 60, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.c_button.setFont(font)
        self.c_button.setObjectName("c_button")
        self.about_frame = QtWidgets.QFrame(self.centralwidget)
        self.about_frame.setGeometry(QtCore.QRect(187, 180, 165, 91))
        self.about_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_frame.setObjectName("about_frame")
        self.github_button = QtWidgets.QPushButton(self.about_frame)
        self.github_button.setGeometry(QtCore.QRect(7, 10, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.github_button.setFont(font)
        self.github_button.setObjectName("github_button")
        self.releases_button = QtWidgets.QPushButton(self.about_frame)
        self.releases_button.setGeometry(QtCore.QRect(7, 42, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.releases_button.setFont(font)
        self.releases_button.setObjectName("releases_button")
        self.version_text = QtWidgets.QLabel(self.about_frame)
        self.version_text.setGeometry(QtCore.QRect(7, 69, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_text.setFont(font)
        self.version_text.setAlignment(QtCore.Qt.AlignCenter)
        self.version_text.setObjectName("version_text")
        self.engine_frame = QtWidgets.QFrame(self.centralwidget)
        self.engine_frame.setGeometry(QtCore.QRect(10, 60, 341, 31))
        self.engine_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.engine_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.engine_frame.setObjectName("engine_frame")
        self.engine_text = QtWidgets.QLabel(self.engine_frame)
        self.engine_text.setGeometry(QtCore.QRect(10, 5, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.engine_text.setFont(font)
        self.engine_text.setObjectName("engine_text")
        self.engine_command = QtWidgets.QLineEdit(self.engine_frame)
        self.engine_command.setGeometry(QtCore.QRect(140, 6, 163, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.engine_command.setFont(font)
        self.engine_command.setObjectName("engine_command")
        self.engine_browse_button = QtWidgets.QPushButton(self.engine_frame)
        self.engine_browse_button.setGeometry(QtCore.QRect(312, 6, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.engine_browse_button.setFont(font)
        self.engine_browse_button.setObjectName("engine_browse_button")

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)

        self.console.setFont(font)

        MainWindow.setMinimumHeight(449)
        MainWindow.setMinimumWidth(612)
        MainWindow.setMaximumHeight(449)
        MainWindow.setMaximumWidth(612)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.console_text.setText(_translate("MainWindow", "Console"))
        self.depth_label.setText(_translate("MainWindow", "Depth"))
        self.depth_value.setText(_translate("MainWindow", "?"))
        self.chess_bot_title.setText(_translate("MainWindow", "ChessBot"))
        self.timeout_text.setText(_translate("MainWindow", "Timeout"))
        self.timeout_value.setText(_translate("MainWindow", "?"))
        self.think_time_text.setText(_translate("MainWindow", "Think Time"))
        self.max_think_time_value.setText(_translate("MainWindow", "?"))
        self.x_button.setText(_translate("MainWindow", "X – Draw Best Move"))
        self.r_button.setText(_translate("MainWindow", "R – Reload Engine"))
        self.c_button.setText(_translate("MainWindow", "C – Auto Draw Move"))
        self.github_button.setText(_translate("MainWindow", "Github"))
        self.releases_button.setText(_translate("MainWindow", "Releases"))
        self.version_text.setText(_translate("MainWindow", "v1.0.1"))
        self.engine_text.setText(_translate("MainWindow", "UCI-Engine"))
        self.engine_command.setText(_translate("MainWindow", "?"))
        self.engine_browse_button.setText(_translate("MainWindow", "..."))
